/*
 * epi2.cnvendian.input.c
 *
 * This file is automatically generated by the 'createCnvEndianInput' script.
 * It contains the declarations of all CVs and TGT exports variables
 * and is used to generate the endian converters for all of these
 * variables.
 *
 * Generated on Thu May 23 11:05:54 PDT 2019
 */

#include "epi2.global.h"
#include "epi2.allcv.h"
#include "epi2.tgtex.h"
