/*
 *  epi2.global.h
 *
 *  Do not edit this file. It is automatically generated by EPIC.
 *
 *  Date : Nov 24 2018
 *  Time : 13:36:59
 */

#ifndef h_epi2_global_h
#define h_epi2_global_h

/*
 * global
 * Globally used definitions
 * These are shared between host and target compilation
 * Items used in this section are candidates for serialization
 * and as such will introduce endian conversion code
 */

#include "acquisition_control.h"
#include "ca_filt.h"
#include "CoilParameters.h"
#include "coilsupportDefs.h"
#include "config_platform_hw.h"
#include "dabrecord_common.h"
#include "entrypttab.h"
#include "epic_advisory_panel.h"
#include "epic_algorithm_control.h"
#include "epic_application_ranges.h"
#include "epic_anatomy.h"
#include "epic_entry_points.h"
#include "epic_geometry_types.h"
#include "epic_hw_defs.h"
#include "epic_ifcc_sizes.h"
#include "epic_pulse_structs.h"
#include "epic_recon_control.h"
#include "epic_regulatory.h"
#include "epic_rsp_sizes.h"
#include "epic_sar_communication.h"
#include "epic_slice_order_types.h"
#include "epic_ssp_defs.h"
#include "epic_system_defs.h"
#include "epic_ui_control.h"
#include "epic_usercv.h"
#include "epic_waveform_types.h"
#include "filter_defs.h"
#include "GElimits.h"
#include "GEtypes.h"             /* type definitions from GEtypes project*/
#include "gradient_pulse_types.h"
#include "gradSpec.h"
#include "hoec_defines.h"  /* HOEC */
#include "IfccPSDShared.h"
#include "log_grad_struct.h"
#include "op_recn.h"
#include "pgen_epic.h"
#include "physics_constants.h"
#include "physioHwDefs.h"
#include "prescan_defs.h"
#include "psdexitarg.h"
#include "recon_filter_defs.h"
#include "ReconHostPSDShared.h"
#include "round_int_macros.h"
#include "seqCfg.h"
#include "slice_factor.h"  
#include "supp_macros.h"
#include "transmit_chain.h"
#include "usage_tag.h"

/*
 * Miscellaneous entries. Candidates for relocation to other, more
 * specific headers.
 */
#include "psd_common_global_includes.h"

/*
 * Copyright 2017 General Electric Company.  All rights reserved.
 */

/*
 * epic_cvconst.eh
 *
 * This EPIC source file declares the variables used to communicate
 * between host applications (scn, ifcc, psc, etc) and PSDs.  This file
 * is used to generate "cv_const.h" which assigns an integer for use
 * in referencing each CV fromi many psdIF APIs.  Therefore, it is 
 * critical that the variable names and order match between the PSD and
 * host applications.  The @revision must be changed accordingly as
 * indicated below.
 *
 * This file is included in epic.h
 *
 */

/*
 * A revision number change is mandatory when variables are added to or
 * removed from @reqcv.  A revision number change is also mandatory when
 * variables ared added to or removed from @reqexport unless a variable
 * is added at to end, in which case a revision number change is
 * not necessary for testing purposes.  
 */

/*
 * Do not insert new @ EPIC directives in this file!
 */


/* omega/theta modulation support */
/* 
 * omegathetamod.eh
 *
 * MACRO to support construction of waveforms on omega / theta to support frequency
 * and phase modulation of an RF pulse to achieve desired offsets.
 * Underlying function is written generally now in order to support an input omega, theta waveform
 * already existing, but MACRO is currently assuming now pre-existing omega/theta.
 *
 *  Language : ANSI C
 *  Author   : Zhenghui Zhang and Matthew Middione
 *  Date     : April 2015
 *
 *  30-Jun-2015  ZZ HCSDM00359612: Multiband feature implementation
 *
 */
/* Local includes */
#include "pulsegen.h"
#include "pgen_tmpl.h"
#include "epicmsg.h"
/* macro to convert phase to range [-pi..pi] */
#define FABS(x)  (((x) < 0.0) ? (-(x)) : (x))
#define FLOOR(x) ((int)(x)-((x) < (int)(x)))
#define MODTWOPI(x) ((x) - FLOOR(((x) + PI)/(2*PI))*2*PI)


/*********************************************************************
 *                       EPI2.E GLOBAL SECTION                        *
 *                                                                   *
 * Common code shared between the Host and Tgt PSD processes.  This  *
 * section contains all the #define's, global variables and function *
 * declarations (prototypes).                                        *
 *********************************************************************/

/* System includes */
#include <string.h>
#include <stdio.h>

/*
 * EPIC header files
 */
#include "em_psd_ermes.in"

#include "stddef_ep.h"
#include "epicconf.h"
#include "pulsegen.h"
#include "support_func.h"
#include "epic_error.h"
#include "epicfuns.h"
#include "psdutil.h" 
#include "acousticResponse.h" /* Should move to a common header file */
#include "acousticLockout.h"
#include "ReconHostPSDShared.h"

#ifdef PSD_HW   /* Auto Voice */
#include "broadcast_autovoice_timing.h"
#endif

/* HOEC */

#include "HoecCorr.h"

/* File to determine how HOEC terms should be distributed for PSD and recon correction under the manual mode */
#ifdef SIM
#define HOEC_CORRTERMS_FILE "hoecCorrTerms.txt"
#else
#define HOEC_CORRTERMS_FILE "/usr/g/bin/hoecCorrTerms.txt"
#endif

#define HOEC_MAX_ILEAVE 8  /* for now...*/
/* File to store debug information for HOEC correction */
#ifdef SIM
#define HOEC_DEBUG_FILE "hoecDebug.txt"
#else
#define HOEC_DEBUG_FILE "/usr/g/bin/hoecDebug.txt"
#endif

/* File containing HOEC recon coefficients, dumped only in debug mode */
#ifdef SIM
#define HOEC_COEF_RECON_FILE "hoecCoefRecon.txt"
#else
#define HOEC_COEF_RECON_FILE "/usr/g/bin/hoecCoefRecon.txt"
#endif


/* MuseGlobal  inlined from Muse.e */
#define MUSE_MIN_NSHOTS 2
#define MUSE_MAX_NSHOTS 8


#include "filter_defs.h"
#include "ChemSat.h"

#include "epi2.h"
#include "psd_proto.h"
#include "epic_iopt_util.h"

#include "grad_rf_epi2.globals.h"

#define EPI2_FLAG    /* Identifies the PSD as EPI2 */

#define MAXFRAMESIZE_DPC 1024 /* max frame size limited by recon when dynamic phace correction is needed */

#ifndef PSD_CFH_CHEMSAT
#define PSD_CFH_CHEMSAT
#endif

#ifndef KEY_PRESENT
#define KEY_PRESENT 0
#endif /* KEY_PRESENT */

/* Some spsp RF1 definitions */
#define PSD_SE_RF1_PW   5000    /* Pulse width */
#define PSD_SE_RF1_fPW  5000 
#define PSD_SE_RF1_LEFT  3100  
#define PSD_SE_RF1_RIGHT 1900  
#define PSD_SE_RF1_R     250   /* Resolution of FL90mc pulse */
#define PSD_GR_RF1_PW   3200      /* Pulse width */
#define PSD_GR_RF1_fPW  3200.0  
#define PSD_GR_RF1_LEFT  1600  
#define PSD_GR_RF1_RIGHT 1600  
#define PSD_GR_RF1_R     400   /* Resolution of GR30l pulse */

/* Nominal pulse width definition */
#define PSD_NOM_PW_SE1B4 3200        /* SE1B4 pulse */
#define PSD_NOM_PW_FL901MC 4000      /* FL901MC pulse */
#define PSD_NOM_PW_GR30 3200         /* GR30 pulse */

/* needed for Inversion.e inline */
#define PSD_FSE_RF2_fPW   4000 
#define PSD_FSE_RF2_R     400

#define RUP_HRD(A)  (((A)%hrdwr_period) ? (int)((A) + hrdwr_period) & ~(hrdwr_period - 1) : (A))

#define NAV_EPI

#undef TR_MAX
#define TR_MAX 30000000
#define TR_MAX_EPI2 17000000 /* Used for avmaxtr, cvmax and In-Range TR */
#define FOV_MAX_EPI2 600
#undef RBW_MIN
#define RBW_MIN 15.625
#undef RBW_MAX
#define RBW_MAX 250.0

#undef MAX_RFPULSE_NUM

/* Maximum b-Value for Scanner Config. */
#undef MAXB_1000
#define MAXB_1000 1000
#undef MAXB_1500
#define MAXB_1500 1500
#undef MAXB_2500
#define MAXB_2500 2500
#undef MAXB_4000
#define MAXB_4000 4000
#undef MAXB_7000
#define MAXB_7000 7000
#undef MAXB_10000
#define MAXB_10000 10000
#undef MAX_CRM_DW
#define MAX_CRM_DW 35000
#undef MINB_VALUE
#define MINB_VALUE 10
#undef BRM_PEAK_AMP
#define BRM_PEAK_AMP 200.0
#undef MAX_DIFF_NEX
#define MAX_DIFF_NEX 16
#undef MAX_DIFF_NEX_64
#define MAX_DIFF_NEX_64 64

/* Range for synthetic bvalue prescription */
#undef LOWER_SYNB_LIMIT_IVIM
#define LOWER_SYNB_LIMIT_IVIM 100.0
#undef UPPER_SYNB_LIMIT_RESTRICT_DIFF
#define UPPER_SYNB_LIMIT_RESTRICT_DIFF 2500.0
#undef SYNBVAL_EXPAND_FACTOR
#define SYNBVAL_EXPAND_FACTOR 2.5
#undef UPPER_SYNB_LIMIT_RESEARCH_MODE
#define UPPER_SYNB_LIMIT_RESEARCH_MODE 4000.0

/* minimum number of additional ky lines to acquire beyond opyres/2: */
#define MIN_HNOVER_DWI 16
#define MIN_HNOVER_DEF 8
#define MIN_HNOVER_GRE 20
#define MIN_HNOVER_RFOV 8 /* HCSDM00150820 */

/* dephaser pulse position definitions */
#define PSD_PRE_180 0
#define PSD_POST_180 1

/* Flow Comp */
#define NO_GMN 0
#define CALC_GMN1 1
#define CALC_GMN2 2

/* YMSmr06515: # of slice locations expansion 
#undef DATA_ACQ_MAX
#define DATA_ACQ_MAX 512
*/

#define MAXSLQUANT_EPI 512

#define TWOPI_GAMMA 26748.0   /* 2*PI*GAMMA */
#define TWO_PI 2.0*PI         /*  added by XJZ  */
#define NUM_DWI_DIRS 4
#define NUM_DWI_AXES 3

/* Diffusion */
#define T2_IMAGE 1
#define ALL_AXIS 3
#define ALL_AXIS_TETRA 4
#define ONE_AXIS 1
#define Z 1
#define X 2
#define Y 3
#define DIR1 0
#define DIR2 1
#define DIR3 2
#define DIR4 3
#define AXIS_X 0
#define AXIS_Y 1
#define AXIS_Z 2

#define HIB_MIN_TR 1000000
#define MAX_SLICES_DTI 50000

#define MAX_NUM_ITERS 40 /* max number of iters for Multi-TR CornerPoints*/

/* FLAIR */
#define FLAIR_MAX_TI 2800000
#define FLAIR_MIN_TI 1500000
#define FLAIR_MIN_TR 6000000
#define EPI_STIR_TI_MAX 500000

/* ASPIR for DWI */
#define ASPIR_DWI_MIN_TI  30000
#define ASPIR_DWI_MAX_TI  290000
#define ASPIR_DWI_1HT_TI      60000
#define ASPIR_DWI_3T_TI       110000
#define ASPIR_DWI_T1EFF_1HT   260000
#define ASPIR_DWI_BCOEFF_1HT  0.95
#define ASPIR_DWI_T1EFF_3T    360000
#define ASPIR_DWI_BCOEFF_3T   0.95

/* For aspir_auto_ti_model */
#define ASPIR_AUTO_TI_FIXED 0
#define ASPIR_AUTO_TI_ADAPTIVE 1 

#define INT_INPUT_NOT_USED 0

#define MAX_FOCUS_EVAL_WATCH 4
#define NUM_EVAL_IN_PREDOWNLOAD 3

/* Big Patient Weight */
#define BIG_PATIENT_WEIGHT 160

#include "ChemSat.h"
#include "chemsat_defs.h"

#define FSE_ASPIR_MAX_TI    1000000
#define FSE_ASPIR_MIN_TI    24000 

/* Empirical data, CF offset at 3cm to avoid COW signal drop */
#define SELECTIVE_OFFSET_3T     160  /* 160 Hz */
#define SELECTIVE_OFFSET_15T    80   /* 80 Hz */
#define SELECTIVE_OFFSET_DIST   3    /* 3cm */

#include "SpSat.h"
#include "psdutil.h"

#define RES_VRGSAT 256
#define RES_NVRGSAT 320
#define PSD_SATOFF 0
#define PSD_SATNEG 1
#define PSD_SATPOS 2
#define PSD_SATHAD 3
#define PSD_SATPARA 4

#define SAT_DEFAULT 1
#define SAT_EXPLICIT 2


#define SAR_PSLR 0.1468
#define SAR_ASLR 0.1641
#define SAR_ABS_SLR 0.3553
#define SAR_MAXPW_SLR 0.5723
#define SAR_DTYCYC_SLR 0.5723
#define RES_SLRSAT 400 

#define REAL_RF 0
#define COMPLEX_RF 1
#define RES_SLRCSAT 1000

#define SINC_SAT 0
#define VRG_SAT 1
#define SLR_SAT 2
#define SLR_CSAT 3 

#define SAT_COAX 0
#define SAT_OBL_METHOD 0

#define SPSAT_LOCAL_LOG_DIR "./"
#define SPSAT_SCANNER_LOG_DIR "/usr/g/service/log/"

#ifndef FALSE
#define FALSE 0
#endif

/***********************************************************************/

#undef NEWERMES			/* Define this when the new ermes */
				/* message is defined  */
#define PSD_INV_RF0_PW    8640  
#define RES_SILVER     432

/*********************************************************************
 *                    PRESCAN.E GLOBAL SECTION                       *
 *                            PSglobal                               *
 *                                                                   *
 * Common code shared between the Host and Tgt PSD processes.  This  *
 * section contains all the #define's, global variables and function *
 * declarations (prototypes).                                        *
 *********************************************************************/
#include "Prescan.h"

#include <stdio.h>
#include <sysDep.h>
#include <sysDepSupport.h>

#include "dynTG_sliceloc.h"

#define amp_killer 0.4
#define pw_killer 3600 
#define FA_FERMI_BLS 630

/* defines for pimrsaps CVs from op_prescan.h */
#define MRSAPS_OFF 0
#define MRSAPS_CFL 1
#define MRSAPS_TG 2
#define MRSAPS_VTG 2
#define MRSAPS_CFH 3
#define MRSAPS_TR 4
#define MRSAPS_FSEPS 9
#define MRSAPS_RCVN 12
#define MRSAPS_RFSHIM 13 
#define MRSAPS_DYNTG 14
#define MRSAPS_CAL 15 
#define MRSAPS_AUTOCOIL 16
#define MRSAPS_AWS 101
#define MRSAPS_AVS 102
#define MRSAPS_AS  103
#define MRSAPS_FTG 104
#define MRSAPS_XTG 116
#define MRSAPS_XTG_SPINE 117

/* defines for cfh_ti */
#define CFHTI_1HT 120000
#define CFHTI_3T  190000
#define CFHTE_1HT 50000
#define CFHTE_3T  30000
#define PSD_ISI_CFH (PSD_ISI0_BIT | PSD_ISI1_BIT)
#define PSCFH_SHIMVOL_DEBUG_X 1
#define PSCFH_SHIMVOL_DEBUG_Y 2
#define PSCFH_SHIMVOL_DEBUG_Z 4
#define PSCFH_SHIMVOL_DEBUG_NONE 0

#define PH_SEQUENTIAL   0 
#define PH_CENTRIC_LOW  1 
#define PH_CENTRIC_HIGH 2 
#define RFSHIM_SLQ 1 
#define DYNTG_SLQ  5
#define MAPTG_SLQ 1

#define B1RF1_SINC 0
#define B1RF1_TBW  1

#define MINFOV_TG 60.0 

/* defines for rcvn_filter */
#define RCVN_MIN_BW  4.0
#define RCVN_MAX_BW  62.5
#define RCVN_MIN_TR  250000

/* defines for Cal */
#define CAL_NONE_INTERLEAVED 0 
#define CAL_TR_INTERLEAVED 1 
#define CAL_NEX_INTERLEAVED 2 

/** Convert from microTesla to Gauss */
#define UTESLA2GAUSS 0.01

#define TR_PSCPASS  100000

/******************************ssGlobal**********************************/

#include "stddef_ep.h"    /* Moved the header files within global section */
#include "ss.h"
#include "epic_error.h"


/* Gradient Mode */
#define GR8607 1
#define GRANAL 2
#define GR8645 3

/* True Null spsp pulse. Min. slice thk is 6.46mm */
#define PSD_SSTN_RF1_PW    16800  
#define PSD_SSTN_RF1_R     840
#define PSD_SSTN_RF1_HlPW  1200    /* half lobe period */
#define PSD_SSTN_RF1_LEFT  8400  
#define PSD_SSTN_RF1_RIGHT 8400  
#define PSD_SSTN_RF1_NUML  14      /* number of lobes in ss_pulse */

/*ss1560010 1.5T 600us ramp 10mT/m opposed null SR17 */
#define PSD_ss1560010_RF1_PW     14400   /* pulse width */ 
#define PSD_ss1560010_RF1_R      3600    /* resolution  */ 
#define PSD_ss1560010_RF1_HlPW   2400    /* half lobe period */
#define PSD_ss1560010_RF1_LEFT   7200    /* left half width */
#define PSD_ss1560010_RF1_RIGHT  7200    /* right half width */
#define PSD_ss1560010_RF1_NUML   6       /* number of lobes in ss_pulse */
#define MAX_B1_ss1560010         0.02599 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss1560010  0.00086 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss1560010     0.00773 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss1560010        0.1569  /* Absolute width */
#define SAR_Pss1560010           0.0885  /* Effective width */
#define SAR_DTCss1560010         0.2472  /* Duty cycle */ 
#define SAR_MAXPWss1560010       0.1525  /* Maximum pulse width*/
#define SAR_ARss1560010          0.1569  /* Area*/
#define NOM_BW_ss1560010         1283.0  /* Bw in Hz */

/*ss15110022 1.5T 1100us ramp 22mT/m opposed null SR20 and SR50*/
#define PSD_ss15110022_RF1_PW    14400   /* pulse width */ 
#define PSD_ss15110022_RF1_R     3600    /* resolution  */ 
#define PSD_ss15110022_RF1_HlPW  2400    /* half lobe period */
#define PSD_ss15110022_RF1_LEFT  7200    /* left half width */
#define PSD_ss15110022_RF1_RIGHT 7200    /* right half width */
#define PSD_ss15110022_RF1_NUML  6      /* number of lobes in ss_pulse */
#define MAX_B1_ss15110022        0.0359  /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss15110022 0.00113 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss15110022    0.00886 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss15110022       0.1137  /* Absolute width */
#define SAR_Pss15110022          0.0610  /* Effective width */
#define SAR_DTCss15110022        0.1739  /* Duty cycle */ 
#define SAR_MAXPWss15110022      0.1492  /* Maximum pulse width*/
#define SAR_ARss15110022         0.1137  /* Area*/
#define NOM_BW_ss15110022        1813.0  /* Bw in Hz */

/*ss1528822 1.5T 288us ramp 22mT/m true null SR77 */
#define PSD_ss1528822_RF1_PW     14400   /* pulse width */ 
#define PSD_ss1528822_RF1_R      3600    /* resolution  */ 
#define PSD_ss1528822_RF1_HlPW   1200    /* half lobe period */
#define PSD_ss1528822_RF1_LEFT   9528    /* left half width */
#define PSD_ss1528822_RF1_RIGHT  4872    /* right half width */
#define PSD_ss1528822_RF1_NUML   12      /* number of lobes in ss_pulse */
#define MAX_B1_ss1528822         0.03807 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss1528822  0.00133 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss1528822     0.00960 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss1528822        0.1280  /* Absolute width */
#define SAR_Pss1528822           0.0636  /* Effective width */
#define SAR_DTCss1528822         0.1828  /* Duty cycle */ 
#define SAR_MAXPWss1528822       0.0757  /* Maximum pulse width*/
#define SAR_ARss1528822          0.1071  /* Area*/
#define NOM_BW_ss1528822         2571.0  /* Bw in Hz */

/*ss1544022 1.5T 440us ramp 22mT/m opposed null SR50*/
#define PSD_ss1544022_RF1_PW     13000   /* pulse width */
#define PSD_ss1544022_RF1_R      3250    /* resolution  */
#define PSD_ss1544022_RF1_HlPW   1000    /* half lobe period */
#define PSD_ss1544022_RF1_LEFT   6500    /* left half width */
#define PSD_ss1544022_RF1_RIGHT  6500    /* right half width */
#define PSD_ss1544022_RF1_NUML   13       /* number of lobes in ss_pulse */
#define MAX_B1_ss1544022         0.06018 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss1544022  0.00176 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss1544022     0.01164 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss1544022        0.0751  /* Absolute width */
#define SAR_Pss1544022           0.0374  /* Effective width */
#define SAR_DTCss1544022         0.1137  /* Duty cycle */
#define SAR_MAXPWss1544022       0.0707  /* Maximum pulse width*/
#define SAR_ARss1544022          0.0751  /* Area*/
#define NOM_BW_ss1544022         2809.9  /* Bw in Hz */

/*ss1534433 1.5T 344us ramp 33mT/m opposed null SR100*/ /* Designed for SV. wxc GEHmr01479 */
#define PSD_ss1534433_RF1_PW      13000      /* pulse width */
#define PSD_ss1534433_RF1_R       3250       /* resolution  */
#define PSD_ss1534433_RF1_HlPW    1000       /* lobe period */
#define PSD_ss1534433_RF1_LEFT    6500       /* left half width */
#define PSD_ss1534433_RF1_RIGHT   6500       /* right half width */
#define PSD_ss1534433_RF1_NUML    13         /* number of lobes in ss_pulse */
#define MAX_B1_ss1534433          0.053400   /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss1534433   0.00164418 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss1534433      0.00112461 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss1534433         0.0846     /* Absolute width */
#define SAR_Pss1534433            0.0444     /* Effective width */
#define SAR_DTCss1534433          0.1274     /* Duty cycle */
#define SAR_MAXPWss1534433        0.0738     /* Maximum pulse width*/
#define SAR_ARss1534433           0.0846     /* Area*/
#define NOM_BW_ss1534433          2614.0     /* Bw in Hz */

/*ss15496468 1.5T 496us ramp 24.8mT/m opposed null SR50*/ /* Designed for Starter and the gmax was
 *designed according to the ramptime and slewrate. ZT */
#define PSD_ss15496248_RF1_PW      13000      /* pulse width */
#define PSD_ss15496248_RF1_R       3250       /* resolution  */
#define PSD_ss15496248_RF1_HlPW    1000       /* lobe period */
#define PSD_ss15496248_RF1_LEFT    6500       /* left half width */
#define PSD_ss15496248_RF1_RIGHT   6500       /* right half width */
#define PSD_ss15496248_RF1_NUML    13         /* number of lobes in ss_pulse */
#define MAX_B1_ss15496248          0.0372605  /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss15496248   0.00136342 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss15496248      0.00945981 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss15496248         0.1212     /* Absolute width */
#define SAR_Pss15496248            0.0645     /* Effective width */
#define SAR_DTCss15496248          0.1988     /* Duty cycle */
#define SAR_MAXPWss15496248        0.0751     /* Maximum pulse width*/
#define SAR_ARss15496248           0.1212     /* Area*/
#define NOM_BW_ss15496248          2116.4     /* Bw in Hz */

/* ss3026838 3.0T 268us ramp 38 mT/m  SR140 *YH,YZ*/
#define PSD_ss3026838_RF1_PW     9480    /* pulse width */ 
#define PSD_ss3026838_RF1_R      2370    /* resolution  */ 
#define PSD_ss3026838_RF1_HlPW   632     /* half lobe period */
#define PSD_ss3026838_RF1_LEFT   4740    /* left half width */
#define PSD_ss3026838_RF1_RIGHT  4740    /* right half width */
#define PSD_ss3026838_RF1_NUML   15      /* number of lobes in ss_pulse */
#define MAX_B1_ss3026838         0.0651 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss3026838  0.0020 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss3026838     0.01456 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss3026838        0.0951  /* Absolute width */
#define SAR_Pss3026838           0.050   /* Effective width */
#define SAR_DTCss3026838         0.1427  /* Duty cycle */ 
#define SAR_MAXPWss3026838       0.0659  /* Maximum pulse width*/
#define SAR_ARss3026838          0.0951  /* Area*/
#define NOM_BW_ss3026838         4950.0  /* Bw in Hz */


/* ss3026033 3.0T 260us ramp 33 mT/m  SR126 YZ -- new spsp pulse*/
#define PSD_ss3026033_RF1_PW     9720    /* pulse width */ 
#define PSD_ss3026033_RF1_R      2430    /* resolution  */ 
#define PSD_ss3026033_RF1_HlPW   648     /* half lobe period */
#define PSD_ss3026033_RF1_LEFT   4520    /* left half width for 90 flip */
#define PSD_ss3026033_RF1_RIGHT  5200    /* right half width for 90 flip */
#define PSD_ss3026033_RF1_NUML   15      /* number of lobes in ss_pulse */
#define MAX_B1_ss3026033         0.0464 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss3026033  0.0015 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss3026033     0.01223 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss3026033        0.1302  /* Absolute width */
#define SAR_Pss3026033           0.0695   /* Effective width */
#define SAR_DTCss3026033         0.1928  /* Duty cycle */ 
#define SAR_MAXPWss3026033       0.0651  /* Maximum pulse width*/
#define SAR_ARss3026033          0.1302  /* Area*/
#define NOM_BW_ss3026033         4192.0  /* Bw in Hz */

/* BJM: New 3T Spatial Spectral pulse - same as above except larger spectral BW */
#define PSD_ss30260334_RF1_PW    9720    /* pulse width */ 
#define PSD_ss30260334_RF1_R     2430    /* resolution  */ 
#define PSD_ss30260334_RF1_HlPW  648     /* half lobe period */
#define PSD_ss30260334_RF1_LEFT  4569    /* left half width */
#define PSD_ss30260334_RF1_RIGHT 5151    /* right half width */
#define PSD_ss30260334_RF1_NUML  15      /* number of lobes in ss_pulse */
/* #define MAX_B1_ss30260334     0.09837 Max B1 at 90 degree nominal flip */
#define MAX_B1_ss30260334        0.12788  /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss30260334 0.00403 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss30260334    0.0203736 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss30260334       0.0819  /* Absolute width */
#define SAR_Pss30260334          0.0429  /* Effective width */
#define SAR_DTCss30260334        0.1171  /* Duty cycle */ 
#define SAR_MAXPWss30260334      0.0652  /* Maximum pulse width*/
#define SAR_ARss30260334         0.0614  /* Area*/
#define NOM_BW_ss30260334        4040.0  /* Bw in Hz - from Matlab Sim */

/* GW new spsp for breast scan TypeI */
#define PSD_ss30248501_RF1_PW    14256   /* pulse width */
#define PSD_ss30248501_RF1_R     3564    /* resolution  */
#define PSD_ss30248501_RF1_HlPW  528     /* half lobe period */
#define PSD_ss30248501_RF1_LEFT  6912    /* left half width */
#define PSD_ss30248501_RF1_RIGHT 7344    /* right half width */
#define PSD_ss30248501_RF1_NUML  27      /* number of lobes in ss_pulse */
/* #define MAX_B1_ss30248501     0.10904   Max B1 at 90 degree nominal flip from spspTool */
#define MAX_B1_ss30248501        0.131635  /* Max B1 at 90 degree nominal flip from rfstat */
#define MAX_INT_B1_SQ_ss30248501 0.00745326 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss30248501    0.0228652 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss30248501       0.0591  /* Absolute width */
#define SAR_Pss30248501          0.0302  /* Effective width */
#define SAR_DTCss30248501        0.0578  /* Duty cycle */
#define SAR_MAXPWss30248501      0.0351  /* Maximum pulse width */
#define SAR_ARss30248501         0.0382  /* Area */
#define NOM_BW_ss30248501        3640.8  /* Bw in Hz - from Matlab Sim */

/* GW new spsp for breast scan TypeII */
#define PSD_ss30248502_RF1_PW    16000   /* pulse width */
#define PSD_ss30248502_RF1_R     4000    /* resolution  */
#define PSD_ss30248502_RF1_HlPW  1000    /* half lobe period */
#define PSD_ss30248502_RF1_LEFT  7782    /* left half width */
#define PSD_ss30248502_RF1_RIGHT 8218    /* right half width */
#define PSD_ss30248502_RF1_NUML  16      /* number of lobes in ss_pulse */
/* #define MAX_B1_ss30248502     0.062448  Max B1 at 90 degree nominal flip from spspTool */
#define MAX_B1_ss30248502        0.0772887  /* Max B1 at 90 degree nominal flip from rfstat */
#define MAX_INT_B1_SQ_ss30248502 0.00452719 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss30248502    0.0168211 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss30248502       0.0971  /* Absolute width */
#define SAR_Pss30248502          0.0474  /* Effective width */
#define SAR_DTCss30248502        0.1075  /* Duty cycle */
#define SAR_MAXPWss30248502      0.0478  /* Maximum pulse width */
#define SAR_ARss30248502         0.0580  /* Area */
#define NOM_BW_ss30248502        2375.6  /* Bw in Hz - from Matlab Sim */

/* ss3027633 for bresat DWI on 750W */
#define PSD_ss3027633_RF1_PW      14256   /* pulse width */
#define PSD_ss3027633_RF1_R       3564 /* resolution  */
#define PSD_ss3027633_RF1_HlPW    528   /* half lobe period */
#define PSD_ss3027633_RF1_LEFT    6906   /* left half width */
#define PSD_ss3027633_RF1_RIGHT   7350   /* right half width */
#define PSD_ss3027633_RF1_NUML    27     /* number of lobes in ss_pulse */
#define MAX_B1_ss3027633          0.141819 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss3027633   0.0073074 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss3027633      0.0226403 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss3027633         0.0519 /* Absolute width */
#define SAR_Pss3027633            0.0255 /* Effective width */
#define SAR_DTCss3027633          0.0617 /* Duty cycle */
#define SAR_MAXPWss3027633        0.0348 /* Maximum pulse width */
#define SAR_ARss3027633           0.0339 /* Area */
#define NOM_BW_ss3027633          3823.5 /* Bw in Hz */

/* cxl04 20000727 ss3018027 3.0T 180us ramp 26.8mT/m true null SR150 
   redesigned so that pw_ss_ramp is multiple of 4us */
#define PSD_ss3018027_RF1_PW     7200    /* pulse width */ 
#define PSD_ss3018027_RF1_R      1800    /* resolution  */ 
#define PSD_ss3018027_RF1_HlPW   600     /* half lobe period */
#define PSD_ss3018027_RF1_LEFT   3600    /* left half width */
#define PSD_ss3018027_RF1_RIGHT  3600    /* right half width */
#define PSD_ss3018027_RF1_NUML   12      /* number of lobes in ss_pulse */
#define MAX_B1_ss3018027         0.04945 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss3018027  0.00155 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss3018027     0.01468 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss3018027        0.1649  /* Absolute width */
#define SAR_Pss3018027           0.0882  /* Effective width */
#define SAR_DTCss3018027         0.2535  /* Duty cycle */ 
#define SAR_MAXPWss3018027       0.0753  /* Maximum pulse width*/
#define SAR_ARss3018027          0.1649  /* Area*/
#define NOM_BW_ss3018027         5659.0  /* Bw in Hz */

/*ss1060010 1.0T 600us ramp 10mT/m opposed null SR17 */
#define PSD_ss1060010_RF1_PW     21600   /* pulse width */ 
#define PSD_ss1060010_RF1_R      5400    /* resolution  */ 
#define PSD_ss1060010_RF1_HlPW   3600    /* half lobe period */
#define PSD_ss1060010_RF1_LEFT   10800   /* left half width */
#define PSD_ss1060010_RF1_RIGHT  10800   /* right half width */
#define PSD_ss1060010_RF1_NUML   6       /* number of lobes in ss_pulse */
#define MAX_B1_ss1060010         0.02749 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss1060010  0.00103 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss1060010     0.00692 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss1060010        0.1174  /* Absolute width */
#define SAR_Pss1060010           0.0634  /* Effective width */
#define SAR_DTCss1060010         0.1726  /* Duty cycle */ 
#define SAR_MAXPWss1060010       0.0678  /* Maximum pulse width*/
#define SAR_ARss1060010          0.0989  /* Area*/
#define NOM_BW_ss1060010         1425.0  /* Bw in Hz */

/*ss10110022 1.0T 1100us ramp 2.2mT/m opposed null SR20 and SR50*/
#define PSD_ss10110022_RF1_PW    21600   /* pulse width */ 
#define PSD_ss10110022_RF1_R     5400    /* resolution  */ 
#define PSD_ss10110022_RF1_HlPW  3600    /* half lobe period */
#define PSD_ss10110022_RF1_LEFT  10800   /* left half width */
#define PSD_ss10110022_RF1_RIGHT 10800   /* right half width */
#define PSD_ss10110022_RF1_NUML  6       /* number of lobes in ss_pulse */
#define MAX_B1_ss10110022        0.03292 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss10110022 0.00124 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss10110022    0.00757 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss10110022       0.0982  /* Absolute width */
#define SAR_Pss10110022          0.0529  /* Effective width */
#define SAR_DTCss10110022        0.1443  /* Duty cycle */ 
#define SAR_MAXPWss10110022      0.0566  /* Maximum pulse width*/
#define SAR_ARss10110022         0.0826  /* Area*/
#define NOM_BW_ss10110022        1677.0   /* Bw in Hz */

/*ss1028822 1.0T 288us ramp 22mT/m true null SR77 */
#define PSD_ss1028822_RF1_PW     21600   /* pulse width */ 
#define PSD_ss1028822_RF1_R      5400    /* resolution  */ 
#define PSD_ss1028822_RF1_HlPW   1800    /* half lobe period */
#define PSD_ss1028822_RF1_LEFT   14470   /* left half width */
#define PSD_ss1028822_RF1_RIGHT  7130   /* right half width */
#define PSD_ss1028822_RF1_NUML   12      /* number of lobes in ss_pulse */
#define MAX_B1_ss1028822         0.04233 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss1028822  0.00171 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss1028822     0.00889 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss1028822        0.0933  /* Absolute width */
#define SAR_Pss1028822           0.0441  /* Effective width */
#define SAR_DTCss1028822         0.1249  /* Duty cycle */ 
#define SAR_MAXPWss1028822       0.0340  /* Maximum pulse width*/
#define SAR_ARss1028822          0.0642  /* Area*/
#define NOM_BW_ss1028822         2800.0  /* Bw in Hz - reduced from 2810 to get 3mm min slthick */


/*ss0560010 0.5T 600us ramp 10mT/m true null SR17 */
#define PSD_ss0560010_RF1_PW     36000    /* pulse width */
#define PSD_ss0560010_RF1_R      3000     /* resolution  */
#define PSD_ss0560010_RF1_HlPW   3600     /* half lobe period */
#define PSD_ss0560010_RF1_LEFT   18000    /* left half width */
#define PSD_ss0560010_RF1_RIGHT  18000    /* right half width */
#define PSD_ss0560010_RF1_NUML   10       /* number of lobes in ss_pulse */
#define MAX_B1_ss0560010         0.02502  /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss0560010  0.00096  /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss0560010     0.00516  /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss0560010        0.0895   /* Absolute width */
#define SAR_Pss0560010           0.0426   /* Effective width */
#define SAR_DTCss0560010         0.1148   /* Duty cycle */
#define SAR_MAXPWss0560010       0.0260   /* Maximum pulse width*/
#define SAR_ARss0560010          0.0652   /* Area*/
#define NOM_BW_ss0560010         2128.0   /* Bw in Hz - gets a 5mm min slthick - actual value should be 2191 Hz */


/*ss1 1.5T Zur's pulse using SR150 CRM config values (KFK/NDG) */
#define PSD_ss1_RF1_PW           13200    /* pulse width */ 
#define PSD_ss1_RF1_R            3300     /* resolution  */ 
#define PSD_ss1_RF1_HlPW         1200     /* half lobe period */
#define PSD_ss1_RF1_LEFT         11200    /* left half width */
#define PSD_ss1_RF1_RIGHT        2000     /* right half width */
#define PSD_ss1_RF1_NUML         10       /* number of lobes in ss_pulse */
#define MAX_B1_ss1               0.0365089   /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss1        0.000895815 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss1           0.00829822  /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss1              0.0986  /* Absolute width */
#define SAR_Pss1                 0.0517  /* Effective width */
#define SAR_DTCss1               0.1437  /* Duty cycle */ 
#define SAR_MAXPWss1             0.0709  /* Maximum pulse width*/
#define SAR_ARss1                0.0619  /* Area*/
#define NOM_BW_ss1               2043    /* Bw in Hz. Decreased by 25% to match 
                                            slice thickness (NDG) */

/*ss1 1.5T 6ms Zur's pulse (for realtime) using SR150 CRM config 
  values (KFK/NDG) */
#define PSD_ss2_RF1_PW           6000    /* pulse width */ 
#define PSD_ss2_RF1_R            1500    /* resolution  */ 
#define PSD_ss2_RF1_HlPW         1200    /* half lobe period */
#define PSD_ss2_RF1_LEFT         2780    /* left half width */
#define PSD_ss2_RF1_RIGHT        3220    /* right half width */
#define PSD_ss2_RF1_NUML         4       /* number of lobes in ss_pulse */
#define MAX_B1_ss2               0.0349204   /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss2        0.000589769 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss2           0.00991438  /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss2              0.1487  /* Absolute width */
#define SAR_Pss2                 0.0806  /* Effective width */
#define SAR_DTCss2               0.2528  /* Duty cycle */ 
#define SAR_MAXPWss2             0.1561  /* Maximum pulse width*/
#define SAR_ARss2                0.1401  /* Area*/
#define NOM_BW_ss2               2554    /* Bw in Hz */


/* HD new spsp pulse for Whole grad mode (Default Pulse for Whole Mode)
 * specs: ss30276221 276 us ramp 3.0T SR80 22G  TypeI pulse 9NRF
 * Type I : Delay INsensitive Pulse*/
#define PSD_ss30276221_RF1_PW    10608   /* pulse width */ 
#define PSD_ss30276221_RF1_R     2652    /* resolution  */ 
#define PSD_ss30276221_RF1_HlPW  624     /* half lobe period */
#define PSD_ss30276221_RF1_LEFT  4823    /* left half width */
#define PSD_ss30276221_RF1_RIGHT 5785    /* right half width */
#define PSD_ss30276221_RF1_NUML  17      /* number of lobes in ss_pulse */
#define MAX_B1_ss30276221        0.05445 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss30276221 0.001658 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss30276221    0.0125  /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss30276221       0.1017  /* Absolute width */
#define SAR_Pss30276221          0.0527  /* Effective width */
#define SAR_DTCss30276221        0.1530  /* Duty cycle */ 
#define SAR_MAXPWss30276221      0.0567  /* Maximum pulse width*/
#define SAR_ARss30276221         0.1017  /* Area*/
#define NOM_BW_ss30276221        4347.8  /* Bw in Hz */


/* HD new spsp pulse for Whole grad mode (Optional pulse for Whole mode)
 * Can turn this on by setting ss_override to 30276222
 * specs: ss30276222 276 us ramp 3.0T SR80 22G  TypeII pulse 7NRF
 * Type II: Delay sensitive Pulse */
#define PSD_ss30276222_RF1_PW     7784    /* pulse width */ 
#define PSD_ss30276222_RF1_R      1946    /* resolution  */ 
#define PSD_ss30276222_RF1_HlPW   1112    /* half lobe period */
#define PSD_ss30276222_RF1_LEFT   3578    /* left half width */
#define PSD_ss30276222_RF1_RIGHT  4206    /* right half width */
#define PSD_ss30276222_RF1_NUML   13      /* number of lobes in ss_pulse */
#define MAX_B1_ss30276222         0.0300  /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss30276222  0.00096 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss30276222     0.0111  /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss30276222        0.2508  /* Absolute width */
#define SAR_Pss30276222           0.1364  /* Effective width */
#define SAR_DTCss30276222         0.3887  /* Duty cycle */ 
#define SAR_MAXPWss30276222       0.1397  /* Maximum pulse width*/
#define SAR_ARss30276222          0.2508  /* Area*/
#define NOM_BW_ss30276222         1886.8  /* Bw in Hz */


/* ZZ new spsp pulses for 3D Water Excitation */
/* ss15048233 048us ramp 1.5T SR77 2.3G */
#define PSD_ss15048233_RF1_PW     5560   /* pulse width */
#define PSD_ss15048233_RF1_R      1390 /* resolution  */
#define PSD_ss15048233_RF1_HlPW   1112   /* half lobe period */
#define PSD_ss15048233_RF1_LEFT   2475   /* left half width */
#define PSD_ss15048233_RF1_RIGHT  3085   /* right half width */
#define PSD_ss15048233_RF1_NUML   5      /* number of lobes in ss_pulse */
#define MAX_B1_ss15048233         0.216688 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss15048233  0.00888426 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss15048233     0.0399724 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss15048233        0.0740 /* Absolute width */
#define SAR_Pss15048233           0.0340 /* Effective width */
#define SAR_DTCss15048233         0.1000 /* Duty cycle */
#define SAR_MAXPWss15048233       0.0482 /* Maximum pulse width*/
#define SAR_ARss15048233          0.0487 /* Area*/
#define NOM_BW_ss15048233         (1.05*7518.8) /* Bw in Hz */

/* ss15048234 048us ramp 1.5T SR77 2.3G */
#define PSD_ss15048234_RF1_PW     7784   /* pulse width */
#define PSD_ss15048234_RF1_R      1946 /* resolution  */
#define PSD_ss15048234_RF1_HlPW   1112   /* half lobe period */
#define PSD_ss15048234_RF1_LEFT   3480   /* left half width */
#define PSD_ss15048234_RF1_RIGHT  4304   /* right half width */
#define PSD_ss15048234_RF1_NUML   7      /* number of lobes in ss_pulse */
#define MAX_B1_ss15048234         0.161204 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss15048234  0.0072322 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss15048234     0.0304804 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss15048234        0.0711 /* Absolute width */
#define SAR_Pss15048234           0.0358 /* Effective width */
#define SAR_DTCss15048234         0.0904 /* Duty cycle */
#define SAR_MAXPWss15048234       0.0344 /* Maximum pulse width*/
#define SAR_ARss15048234          0.0468 /* Area*/
#define NOM_BW_ss15048234         (1.05*7518.8) /* Bw in Hz */

/* ss15048235 048us ramp 1.5T SR77 2.3G */
#define PSD_ss15048235_RF1_PW     10008   /* pulse width */
#define PSD_ss15048235_RF1_R      2502 /* resolution  */
#define PSD_ss15048235_RF1_HlPW   1112   /* half lobe period */
#define PSD_ss15048235_RF1_LEFT   4478   /* left half width */
#define PSD_ss15048235_RF1_RIGHT  5530   /* right half width */
#define PSD_ss15048235_RF1_NUML   9     /* number of lobes in ss_pulse */
#define MAX_B1_ss15048235         0.146522 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss15048235  0.0058972 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss15048235     0.0242737 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss15048235        0.0608 /* Absolute width */
#define SAR_Pss15048235           0.0274 /* Effective width */
#define SAR_DTCss15048235         0.0787 /* Duty cycle */
#define SAR_MAXPWss15048235       0.0268 /* Maximum pulse width*/
#define SAR_ARss15048235          0.0400 /* Area*/
#define NOM_BW_ss15048235         (1.05*7518.8) /* Bw in Hz */

/* ss30104233 104us ramp 3.0T SR77 2.3G */
#define PSD_ss30104233_RF1_PW     2880   /* pulse width */
#define PSD_ss30104233_RF1_R      720 /* resolution  */
#define PSD_ss30104233_RF1_HlPW   576   /* half lobe period */
#define PSD_ss30104233_RF1_LEFT   1283   /* left half width */
#define PSD_ss30104233_RF1_RIGHT  1597   /* right half width */
#define PSD_ss30104233_RF1_NUML   5      /* number of lobes in ss_pulse */
#define MAX_B1_ss30104233         0.490783 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss30104233  0.0201168 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss30104233     0.0835737 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss30104233        0.0631 /* Absolute width */
#define SAR_Pss30104233           0.0290 /* Effective width */
#define SAR_DTCss30104233         0.0847 /* Duty cycle */
#define SAR_MAXPWss30104233       0.0403 /* Maximum pulse width*/
#define SAR_ARss30104233          0.0415 /* Area*/
#define NOM_BW_ss30104233         (1.05*16949.2) /* Bw in Hz */

/* ss30104234 104us ramp 3.0T SR77 2.3G */
#define PSD_ss30104234_RF1_PW      4032   /* pulse width */
#define PSD_ss30104234_RF1_R       1008 /* resolution  */
#define PSD_ss30104234_RF1_HlPW    576   /* half lobe period */
#define PSD_ss30104234_RF1_LEFT    1807   /* left half width */
#define PSD_ss30104234_RF1_RIGHT   2225   /* right half width */
#define PSD_ss30104234_RF1_NUML    7     /* number of lobes in ss_pulse */
#define MAX_B1_ss30104234          0.365118 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss30104234   0.016376 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss30104234      0.063728 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss30104234         0.0606 /* Absolute width */
#define SAR_Pss30104234            0.0305 /* Effective width */
#define SAR_DTCss30104234          0.0754 /* Duty cycle */
#define SAR_MAXPWss30104234        0.0288 /* Maximum pulse width*/
#define SAR_ARss30104234           0.0399 /* Area*/
#define NOM_BW_ss30104234          (1.05*16949.2) /* Bw in Hz */

/* ss30104235 104us ramp 3.0T SR77 2.3G */
#define PSD_ss30104235_RF1_PW      5184   /* pulse width */
#define PSD_ss30104235_RF1_R       1296 /* resolution  */
#define PSD_ss30104235_RF1_HlPW    576   /* half lobe period */
#define PSD_ss30104235_RF1_LEFT    2317   /* left half width */
#define PSD_ss30104235_RF1_RIGHT   2867   /* right half width */
#define PSD_ss30104235_RF1_NUML    9     /* number of lobes in ss_pulse */
#define MAX_B1_ss30104235          0.331868 /* Max B1 at 90 degree nominal flip */
#define MAX_INT_B1_SQ_ss30104235   0.0133533 /* Max integral B1^2 at 90 degree nominal flip */
#define MAX_RMS_B1_ss30104235      0.0507515 /* Max rms B1 at 90 degree nominal flip */
#define SAR_ABS_ss30104235         0.0519 /* Absolute width */
#define SAR_Pss30104235            0.0234 /* Effective width */
#define SAR_DTCss30104235          0.0640 /* Duty cycle */
#define SAR_MAXPWss30104235        0.0224 /* Maximum pulse width*/
#define SAR_ARss30104235           0.0341 /* Area*/
#define NOM_BW_ss30104235          (1.05*16949.2) /* Bw in Hz */


/* Other spsp pulse */
#define PSD_SSMISC_RF1_PW         15000  
#define PSD_SSMISC_RF1_R          750
#define PSD_SSMISC_RF1_HlPW       1500    /* half lobe period */
#define PSD_SSMISC_RF1_LEFT       7500  
#define PSD_SSMISC_RF1_RIGHT      7500  
#define PSD_SSMISC_RF1_NUML       10      /* number of lobes in ss_pulse */

#define MAX_OMEGA_OFFSET 11742.8    /* Max Offest (mm) (+/- 4999.609 kHz) of Omega Board */
        /* 11742.8.0 = (0.596) * (8388607) (24 bits signed) /(4257.59 * 1 g/cm)*0.1 */
        /*  (mm) = (tardis/unit)*(24 bit)/(gamma * 1 g/cm) * 0.1 mm/cm */ 

/******************************ssCV**************************************/

/* Local header files */
#include "DTI.h"
#include "pgen_calcbval.h"
#include "ftde.h" /* granty edit include code for full time diffusion encoding */

#define MAXCHAR 150
#define MAX_TENSOR_VECTOR_MAG 1.01 /*In the product tensor.dat, the maximum vector is even less than 1.001*/
#define MIN_DTI_DIRECTIONS 6
#define MAX_DTI_LEGACY 150
#define MAX_DTI_CLINICAL 300 /* requires maxtensor option key */


#define TENSOR_FILE_MAX 99              /* Reserve for GE definitions */ 
#define TENSOR_FILE_RSRCH_START 100     /* Research use start from here */
#define TENSOR_FILE_RSRCH_MAX 65536     /* Research use end here */

int gCoilType = PSD_XRMW_COIL;

/* AssetGlobal  inlined from Asset.e */
#include "AccelCommon.h"

#define ASSET_SUPPORT_PHASE 0
#define ASSET_SUPPORT_SLICE 1

/* AssetGlobal  inlined from Asset.e */

/* ARCGlobal inlined from ARC.e */
/* ARC split methods */
#define ARC_NONE 0
#define ARC_PHASE 1
#define ARC_SLICE 2
#define ARC_PHASE_THEN_SLICE 3
#define ARC_SLICE_THEN_PHASE 4
#include "AccelCommon.h"

#ifndef PSD_HALF_NEX
#define PSD_HALF_NEX 0.5
#endif

/* ARCGlobal inlined from ARC.e */
#include "stddef_ep.h"
#include "RfovFuncs.h"

#define MIN_RFOV 40
#define DEFAULT_MAXNSLICES_RFOV 16
#define FOCUS_ONE_ACQ_MIN_TR 4500000

/**********************************************/
/* @inline MK_GradSpec.e GspecGlobal */ /* granty maybe */
#include <float.h>
#include "stddef_ep.h"
#include "MultibandFuncs.h"
#include "psdutil.h"

#define MAX_SLICE_FOV_SHIFT_FACTOR 12.0

/* Max verse rf2 slewrate when slice thickness = VERSERF2_BASE_SLICE_THICK */
#define VERSERF2_BASE_SLICE_THICK 1.0  /* mm */
#define MAX_HB2_VERSERF2_SR 90 /* T/m/s */
#define MAX_HB3_VERSERF2_SR 115 /* T/m/s */

/* Put ramps on the frequency modulation waveforms to maintain the correct phase */
WF_PULSE thetarf2       = INITPULSE;
WF_PULSE thetarf2a      = INITPULSE;
WF_PULSE thetarf2d      = INITPULSE;

#ifdef EPI2_FLAG
WF_PULSE thetarf2left   = INITPULSE;
WF_PULSE thetarf2lefta  = INITPULSE;
WF_PULSE thetarf2leftd  = INITPULSE;
WF_PULSE thetarf2right  = INITPULSE;
WF_PULSE thetarf2righta = INITPULSE;
WF_PULSE thetarf2rightd = INITPULSE;
#endif

/* Multiplex modulation waveforms */
WF_PULSE             index_rf2[10];     /* this points to the whole pulse structure */;
WF_HW_WAVEFORM_PTR     ptr_rf2[10];     /* this points to the actual waveform memory */

/**********************************************/

/* t1flair_stir */

#include "InversionSeqOpt.h"

#define T1_CSF_30000   4200000
#define T1_CSF_15000   4200000
#define T1_CSF_10000   4200000
#define T1_CSF_15000_SINGLE_INV    4500000

#define T1_FAT_15000   260000
#define T1_FAT_30000   360000

#define IMGSLICE 0
#define EDGESLICE 1
#define DUMMYSLICE 2

#define T1FLAIR_FIXED_T1_MODEL 0          /* T1FLAIR Auto TI is calculated by Fixed T1 model */
#define T1FLAIR_EFFECTIVE_T1_MODEL 1      /* T1FLAIR Auto TI is calculated by Effective T1 model */
#define T1FLAIR_EFFECTIVE_TR_MODEL_FAT 2  /* T1FLAIR Auto TI is calculated by new fat model */
#define T1FLAIR_LEGACY_MODEL 3            /* T1FLAIR Auto TI is calculated by legacy model */
#define T2FLAIR_FIXED_T1_MODEL 4          /* T2FLAIR Auto TI is calculated by Fixed T1 model */
#define T2FLAIR_EFFECTIVE_T1_MODEL 5      /* T2FLAIR Auto TI is calculated by Effective T1 model */
#define T2FLAIR_SINGLE_DOUBLE_INV_MODEL 6 /* T2FLAIR Auto TI is calculated by single/double inversion model */
#define T2FLAIR_SINGLE_INV_MODEL 7        /* T2FLAIR Auto TI is calculated by single inversion model for optflair+ (1 pack) */

#define ANALYTICAL_SEQTIME 0 /* Analytical algorithm for seqtime calculation */
#define NUMERICAL_SEQTIME 1 /* Numerical algorithm for seqtime calculation */

#define AUTOTR_MAX_NUMACQS 100 /* Defined to avoid infinite loop in T1flair_analytical_AutoTR */


/* 2009-Mar-10, Lai, GEHmr01484: In-range autoTR support */
#include "AutoAdjustTR.h"

#define DUMMY_SLICE_OFF 0
#define DUMMY_SLICE_1ACQ 1
#define DUMMY_SLICE_MULTI_ACQ 2

/* Definitions for Debugging Support of AutominTR
 * DEBUG_PROD will have minimal debug support for
 * critical errors. DEBUG_DEV is for Debug Messages
 * in Development Mode - Rel 14.0
 */

#define DEBUG_NONE 0
#define DEBUG_PROD 1
#define DEBUG_DEV  2


/***SVBranch: HCSDM00259119  eco mpg ***/
#include "eco_mpg.h"
/*** end of global ***/



/****** CVs ******/
/**********************/

/* SXZ::MRIge72411: for edge ghost optimization */
#define NODESIZE 3
#define VRGF_AFTER_PCOR_ALT 32768
#define FAST_VRGF_ALT 2048
#define DEBUG_CORE 

/* RPG volume acquisition for Distortion Correction (rpg_flag) */
#define RPG_REV_THEN_FWD  1
#define RPG_FWD_THEN_REV  2

/* GEHmr01833, GEHmr02647: XFD Power Limit */
#define XFD_POWER_LIMIT          8.5 /* kW */
#define XFD_POWER_LIMIT_DWI_BASE 6.5 /* kW */

/* GEHmr01834, GEHmr02647: GMAX for DWI */
#define XFD_GMAX_DTI 3.0 /* G/cm */
#define XFD_GMAX_DWI 2.8 /* G/cm */

/*SVBranch: GEHmr04247 */
#define XFD_MINSEQ_LIMIT_DWI   15000000 /* us * kW */
#define XFD_MINSEQ_LIMIT_FLAIR 13000000 /* us * kW */

FILE *fp_coreinfo;
FILE *fp_diff_order; /*Diffusion cycling*/
FILE *fp_cfdata; /*RTB0 correction*/
FILE *fp_utloopinfo; /*RTB0 correction*/

#define DEFAULT_IREF_ETL 3

/* MRIhc56520: SR for EPI with ART on 750w */
#define XRMW_3T_EPI_ART_SR 5.0
#define VRMW_3T_EPI_ART_SR 5.0

#define SR_DERATING_MAX_ITER 5


#include <stddef_ep.h>
#include "Monitor.h"

#include "epic_error.h"

#include "em_spu.in" 

#define MAX_DATA_POINTS 32766
#define MAX_NAV_HRATE 240 /* max heartrate */ 
#define NUM_AVG_BLINE 40
#define NUM_THROWAWAYS 5
#define NUM_BASELINE_PTS (NUM_AVG_BLINE + NUM_THROWAWAYS)
#define DEFAULT_FFT_LENGTH      128
#define DEFAULT_FFT_LENGTH_256  256   /* MRIhc07115 */
#define MIN_ACQ_FOV 200.0    /* min acq fov */
#define M_PI 3.14159265358979323846
#define DEG_TO_RAD 0.01745

#define MKEMC 0x06
#define YMSMC 0x02

/* FOR MERGE */
#define SMARTPREP_APS_OBJECT_PATH  "/usr/g/bin"

#define INPHASE_TE_3T 2200 

typedef enum CYLR_RF_TYPE
{
    CYLR_CONSTANT_DENSITY = 0,
    CYLR_VARIABLE_DENSITY_SR48,
    CYLR_VARIABLE_DENSITY_SR75,
    CYLR_VARIABLE_DENSITY_SR107,
    CYLR_VARIABLE_DENSITY_SR118,
    CYLR_VARIABLE_DENSITY_SR145,
    CYLR_VARIABLE_DENSITY_SR190,
    NUM_CYLR_RF_TYPE
} CYLR_RF_TYPE_E;


/************************************************************************/

#include "Navigator.h"
#include "NavigatorCommon.h"
#define MAX_DATA_CLIPPED 32746
#define MAX_PGEN_TIME_TRIG 50000
#define MAX_PGEN_TIME_GATE 1000
#define MIN_WAIT_TIME 1000  /* 1000 */

#define MAX_CH_GRP 4  
long nav_channel_bit[MAX_CH_GRP] = {0x0, 0x0, 0x0, 0x0};
long navscm_channel_bit[MAX_CH_GRP] = {0x0, 0x0, 0x0, 0x0};


#endif /* h_epi2_global_h */

